[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
settings_section = "initialization_options"

[[semantic_tokens]]
token = "enum"
face = "enum"

[[semantic_tokens]]
token = "parameter"
face = "parameter"

[language.rust.settings.initialization_options]
checkOnSave.command = "clippy"
diagnostics.disabled = ["inactive-code"]

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
args = ["serve"]

[language.scala]
filetypes = ["scala"]
roots = ["build.sbt"]
command = "metals-kakoune"

[language.cpp]
filetypes = ["cpp", "c"]
roots = [".git"]
command = "clangd"

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.latex]
filetypes = ["latex"]
roots = ["document.tex"]
command = "texlab"
