[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"

[language.rust.initialization_options]
checkOnSave.command = "clippy"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
args = ["serve"]

[language.scala]
filetypes = ["scala"]
roots = ["build.sbt"]
command = "metals-kakoune"
