source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    # set-option global lsp_cmd "/home/gskw/.config/kak/plugins/kak-lsp/target/debug/kak-lsp -s %val{session}"
    hook global WinSetOption filetype=(rust|go|scala) %{
        echo -debug "Enabling LSP for filetype %opt{filetype}"
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        set-option window lsp_hover_max_lines 10
        map window user h ':lsp-hover<ret>' -docstring 'LSP Hover'

        lsp-enable-window
    }

    set global lsp_diagnostic_line_error_sign '⨯'
    set global lsp_diagnostic_line_warning_sign ''

    map global user d ':lsp-diagnostics<ret>' -docstring 'Diagnostics'
    map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP Mode'
}

plug "Gskartwii/droplet.kak" theme
plug "TeddyDD/kakoune-selenized" theme
plug "evanrelf/primer.kak" theme
plug "caksoylar/kakoune-snow" theme
plug "nesyamun/nord-kakoune" theme

colorscheme primer

plug "danr/kakoune-easymotion" config %{
	map global user e ':enter-user-mode easymotion<ret>' -docstring 'Easymotion'
}

plug "andreyorst/fzf.kak" config %{
    map global normal <c-p> ': fzf-mode<ret>'
    map global user , ': fzf-mode<ret>v' -docstring 'FZF Git'

} defer "fzf_vcs" %{
	set-option global fzf_git_command 'git ls-files --cached --others --modified --exclude-standard'
}

plug "alexherbo2/wl-clipboard.kak" config %{
    require-module 'wl-clipboard'
}

plug "jbomanson/search-doc.kak" defer search-doc %{} demand

plug "andreyorst/smarttab.kak" config %{
    hook global WinSetOption filetype=rust expandtab
    hook global WinSetOption filetype=scala expandtab
    hook global WinSetOption filetype=go noexpandtab
    hook global WinSetOption filetype=c expandtab
    hook global WinSetOption filetype=json expandtab
}

plug "KJ_Duncan/kakoune-plantuml.kak" domain "bitbucket.org"

set-option global tabstop 4
set-option global indentwidth 4
set-option global modelinefmt " %%val{bufname}{StatusLineValue}:%%val{cursor_line}:%%val{cursor_char_column}{StatusLine} %%sh{expr $kak_cursor_line \* 100 / $kak_buf_line_count}%%%%  {{context_info}}  {{mode_info}}  {StatusLineValue}%%val{session}{StatusLine}"
set-option global ui_options ncurses_set_title=false ncurses_enable_mouse=false
hook global ModuleLoaded kitty %{
    set-option global kitty_window_type os
}

hook global WinSetOption filetype=markdown %{
    set-option window autowrap_column 80
    autowrap-enable
}

map global user q ':db<ret>' -docstring 'Close buffer'

hook global WinSetOption filetype=rust %{
    set-option window formatcmd 'rustfmt'
    set-option window tabstop 4
    set-option window indentwidth 4
}
hook global WinSetOption filetype=go %{
    set-option window formatcmd 'gofmt'
    set-option window tabstop 4
    set-option window indentwidth 4
}
hook global WinSetOption filetype=scala %{
    set-option window tabstop 2
    set-option window indentwidth 2

    add-highlighter -override shared/scala/string region %{(?<!')"} %{(?<!\\)(\\\\)*"} fill string
}
hook global WinSetOption filetype=c %{
    set-option window tabstop 4
    set-option window indentwidth 4
}
hook global WinSetOption filetype=latex %{
    map window insert <a-a> 'ä'
    map window insert <a-o> 'ö'
}
hook global WinSetOption filetype=json %{
    set-option window tabstop 4
    set-option window indentwidth 4
}

hook global BufCreate .*waybar/config %{
    set buffer filetype json
}
