export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
export WLR_NO_HARDWARE_CURSORS=1
export MATLAB_LOG_DIR=/tmp
export TEXMFVAR=$HOME/.cache/texlive
export TEXMFCONFIG=$home/.config/texlive

export EDITOR=kak
export BROWSER=librewolf
export KEYFILE=$HOME/.config/void/KEYFILE
export GOPATH=$HOME/go

if [[ -x $HOME/.config/zsh/zshenv.local ]]; then
    source $HOME/.config/zsh/zshenv.local
fi
