export PATH="/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.foreman/bin:$HOME/bin:/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib:$LD_LIBRARY_PATH"
export MANPATH="/usr/local/man/:$HOME/.local/share/man/:$MANPATH"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export MATLAB_LOG_DIR=/tmp
export TEXMFVAR=$HOME/.cache/texlive
export TEXMFCONFIG=$home/.config/texlive
export WLR_NO_HARDWARE_CURSORS=1

export EDITOR=kak
export BROWSER=librewolf
export KEYFILE=$HOME/.config/void/KEYFILE
export GOPATH=$HOME/go

if [[ -x $HOME/.config/zsh/zshenv.local ]]; then
    source $HOME/.config/zsh/zshenv.local
fi
