fpath=( $HOME/.config/zsh $fpath )

kakc() {
    /usr/bin/env kak -c $@
}

ZSH=$HOME/.local/share/oh-my-zsh
CASE_SENSITIVE="true"
export PATH="/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/bin:/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib:$LD_LIBRARY_PATH"
export MANPATH="/usr/local/man/:$HOME/.local/share/man/:$MANPATH"
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
export MCFLY_LIGHT=TRUE
export MCFLY_KEY_SCHEME=vim

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git ssh-agent gpg-agent)

source $ZSH/oh-my-zsh.sh

alias ls=exa
alias icat='kitty +kitten icat'
alias btm='btm --color gruvbox-light'

voiddb() {
	void $HOME/.config/void/db/$1.db
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh

if [[ -x ~/.config/zsh/zshrc.local ]]; then
	source ~/.config/zsh/zshrc.local
fi

eval "$(zoxide init zsh)"
eval "$(mcfly init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/gskw/.sdkman"
[[ -s "/home/gskw/.sdkman/bin/sdkman-init.sh" ]] && source "/home/gskw/.sdkman/bin/sdkman-init.sh"

if [[ $(ps --no-header --pid=$PPID --format=cmd) != "fish" ]]
then
	exec fish
fi
