ZSH=$HOME/.local/share/oh-my-zsh
CASE_SENSITIVE="true"
export PATH="/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/bin:/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib:$LD_LIBRARY_PATH"
export MANPATH="/usr/local/man/:$HOME/.local/share/man/:$MANPATH"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git ssh-agent gpg-agent z)

source $ZSH/oh-my-zsh.sh

export EDITOR=kak
export GOPATH=$HOME/go

alias ls=exa
alias icat='kitty +kitten icat'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh

if [[ -x ~/.config/zsh/zshrc.local ]]; then
	source ~/.config/zsh/zshrc.local
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/gskw/.sdkman"
[[ -s "/home/gskw/.sdkman/bin/sdkman-init.sh" ]] && source "/home/gskw/.sdkman/bin/sdkman-init.sh"
